name: Bot Run Noon to 6PM

on:
  schedule:
    - cron: '0 12 * * *'  # noon UTC
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install && npm update
      - run: node bot.js
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
